copy "..\x2D-Game-Engine\build\Win32\Release\x2D Game Engine.exe" "overworld.exe"
copy "..\x2D-Game-Engine\build\Win32\Release\x2d.dll" "x2d.dll"
copy "..\x2D-Game-Engine\3rdparty\angelscript\sdk\angelscript\lib\angelscript.dll" "angelscript.dll"
copy "..\x2D-Game-Engine\3rdparty\Box2D\Box2D\plugin\lib\box2d.dll" "plugins\box2d.dll"
copy "..\x2D-Game-Engine\3rdparty\Box2D\Box2D\plugin\lib\box2dd.dll" "plugins\box2d.dll.debug"
copy "..\x2D-Game-Engine\3rdparty\spine\plugin\lib\spine.dll" "plugins\spine.dll"
copy "..\x2D-Game-Engine\3rdparty\spine\plugin\lib\spined.dll" "plugins\spine.dll.debug"